### ISSUE TITLE
Error when trying to encode with OPUS

### ISSUE THREAD

**Issue by Hotpocketdeath** [Kurtnoise-zeus/megui#58]
I recently updated to the latest line of MeGUI and now no longer able to encode most sources into OPUS.  Other encoders seems to work, such as FFMPEG:AAC and EAC3.  Seems to only error when trying to use OPUS.

[error.log](https://github.com/user-attachments/files/24154584/error.log)

I've tried multiple sources, some of them still work, but most fail.  

Just some things I notice.  
Line "at MeGUI.AviSynthAudioEncoder.Encode() in E:\megui\packages\audio\AudioEncoderInterface.cs:line 512"

I have an E: drive already that is used to store my media files while I process them, but this path does not exist.  I don't know where it's coming from, if it's some kind of temporary path, etc.  It's referenced in every error I receive.

**Comment by Kurtnoise-zeus** [comment]
Hi,

Im looking at this issue.

The path returned is coming from the debugging stack. This is where my code is stored actually. Nothing to worry about that.

**Comment by Kurtnoise-zeus** [comment]
Alright. I found the culprit. Its fixed now. Thank you.

**Comment by Hotpocketdeath** [comment]
Hey,  

I've updated to the latest Megui and just tried another encode and the error remains.


[Error] [6/8/2026 4:56:20 PM] An error occurred
-[Error] [6/8/2026 4:56:20 PM] Exception message: The pipe has been ended.
-[Error] [6/8/2026 4:56:20 PM] Stacktrace
--[NoImage]    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
--[NoImage]    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
--[NoImage]    at MeGUI.AviSynthAudioEncoder.Encode() in E:\megui\packages\audio\AudioEncoderInterface.cs:line 512
-[Error] [6/8/2026 4:56:20 PM] Inner exception: null
